name: CI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@master
        with: 
            path: 'update.json'
            prop_path: 'version'
      - name: Archive
        run:  |
          sudo zip -r MIUICamera_sm6225${{steps.version.outputs.prop}}.zip *  
      - name: Release
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.version.outputs.prop}}
          name: ${{steps.version.outputs.prop}}
          files: MIUICamera_sm6225${{steps.version.outputs.prop}}.zip
          gzip: false
          draft: false
          prerelease: false
          allow_override: true
      - name: Cleanup
        run:  |
          rm MIUICamera_sm6225${{steps.version.outputs.prop}}.zip